### ISSUE TITLE
linking env. measurements to location and time of collection with SEAMAP

### ISSUE THREAD

**Issue by demutsertlab** [NCEAS/oss-fishteam#1]
1. We've chosen to link ENVREC data with STAREC location data so that we can have a link between data in ENVREC and BGSREC

**Comment by tttang0602** [comment]
- [x] Link the location data (DECSLAT, DECSLON) from STAREC with the environment records from ENVREC

- [x] Check the completeness of different environment factors (temp, sal, oxy, chol)

**Comment by tttang0602** [comment]
A quick check on the collection of seamap environmental measurements by year and by location.
[SEAMAP_env.pdf](https://github.com/NCEAS/oss-fishteam/files/1160715/SEAMAP_env.pdf)
[SEAMAP_year.pdf](https://github.com/NCEAS/oss-fishteam/files/1160714/SEAMAP_year.pdf)

**Comment by aesacco** [comment]
@tttang0602 I love those pdfs you made! Fantastic thinking :)

**Comment by aesacco** [comment]
## Found code on StackOverflow to convert string dates to separate numeric date fields and vice-versa

toDate <- function(dates1) {
  ISOdate(year, month, day)
}

toNumerics <- function(Date) {
  stopifnot(inherits(Date, c("Date", "POSIXt")))
  day <- as.numeric(strftime(Date, format = "%d"))
  month <- as.numeric(strftime(Date, format = "%m"))
  year <- as.numeric(strftime(Date, format = "%Y"))
  list(year = year, month = month, day = day)
}

**Comment by aesacco** [comment]
## Test is the name of my dataframe in R, so change it to whatever you have yours named as! 👍 
test$Date <- as.POSIXct(test$MO_DAY_YR,format='%m/%d/%Y')
test$Time <- sapply(strsplit(as.character(test$MO_DAY_YR), " "), "[", 2)
testdates<-data.frame(toNumerics(test$Date))
test$year<-testdates$year
test$month<-testdates$month
test$day<-testdates$day

**Comment by aesacco** [comment]
In honor of Tingting's awesome plots of data availability of data above, I've created by month, and attached the csv data file, of by-month, by-year environmental data availability (counts) from SEAMAP. 

![enviro_data_1999_to_2017](https://user-images.githubusercontent.com/28009047/28437324-0bd71bde-6d4f-11e7-97da-119721439de1.png)
![enviro_data_1982_to_1999](https://user-images.githubusercontent.com/28009047/28437325-0bd6f618-6d4f-11e7-80ea-a290569fa5dd.png)



[Enviro.data.month.year.frequency.txt](https://github.com/NCEAS/oss-fishteam/files/1163610/Enviro.data.month.year.frequency.txt)

**Comment by aesacco** [comment]
Per month - a lot more useful I think!
![envdatapermonth](https://user-images.githubusercontent.com/28009047/28438083-be052678-6d51-11e7-9ae0-894ee90ec944.png)

**Comment by ailich** [comment]
@aesacco the r package lubridate (part of tidyverse) is supposed to make dealing with dates easier and more straightforward.

**Comment by aesacco** [comment]
@ailich been there, done that 💯 

but danke!

(I like reinventing the wheel, so to speak)
