### ISSUE TITLE
Meta-Analysis: Heat map

### ISSUE THREAD

**Issue by kfrasier** [NCEAS/oss-fishteam#10]
**Input:** Meta-analysis dataframe from Issue #5.

**Output:** Spatial heat map study locations

**Comment by kfrasier** [comment]
What should the two axes of the heatmap be?

**Comment by cnglaspie** [comment]
Region/State? Life stage? There are probably going to be a lot of drivers, so it would look silly with one long axis (temp, sal, do, fishing effort, etc) and one short (juvenile, adult).
