### ISSUE TITLE
Paula!!

### ISSUE THREAD

**Issue by aesacco** [NCEAS/oss-fishteam#14]
Where is the bathymetry data?????

Hey, hey, @paulacetus

**Comment by aesacco** [comment]
I also need that polygon of our study area so I can start clipping our geospatial data :)

**Comment by ailich** [comment]
@aesacco Bathymetry data for northern Gulf

https://www.boem.gov/Gulf-of-Mexico-Deepwater-Bathymetry/

**Comment by paulacetus** [comment]
uploaded the extent shape files (polygon and points): see details in issue #16

**Comment by aesacco** [comment]
Paula made the bathymetry and extent Shapefiles!! 

Done and done
