### ISSUE TITLE
build seamap extent

### ISSUE THREAD

**Issue by paulacetus** [NCEAS/oss-fishteam#16]
create a shape file in GIS.
needed to extract data from seamap DB that pertains to the Gulf region.

**Comment by paulacetus** [comment]
uploaded shape files to google drive : polygon (extentGOM.shp) and vertices (extentseamapPt.shp).
coordinates in decimal degrees (GCS_North_American_1983) in the point shp file.
extent: X = [23.7, 30.54]; Y = [-80.97, -97.66]

**Comment by aesacco** [comment]
Great job, Paula!!
