### ISSUE TITLE
Identify drivers for model

### ISSUE THREAD

**Issue by kfrasier** [NCEAS/oss-fishteam#18]

**Comment by paulacetus** [comment]
response variable = CPUE RS (source: SEAMAP, months: June, July; all years). CPUE = abundance/trawl duration.
environmental variables = Mid-salinity; mid-temp; SS-chl; bottom-DO (source: SEAMAP; avg June/July by year); 
bathymetry, oil spills, reef, oil platforms, shrimp effort, bottom type.
