### ISSUE TITLE
creating red snapper CPUE

### ISSUE THREAD

**Issue by demutsertlab** [NCEAS/oss-fishteam#2]
linking STAREC to BGSREC and INVREC
- Best unit of effort is time: tow duration is in INVREC (Min_FISH)
- Prior to the fall 2008 survey, multiple tows may have been done at a SEAMAP station (S_STA_NO) in order to cover a depth zone (and are listed as multiple stations).  In this case the tows, could be anywhere from 10 to 55 minutes.  After 2008, the tow time was standardized to 30 minutes.

**Comment by ailich** [comment]
Checked @demutsertlab  merge of the tables and it seems to all match up correctly

**Comment by demutsertlab** [comment]
The R code is updated and posted. I have calculated CPUE as abundance per minute trawled. It is selected by gear so that it is only shrimp trawl of size 40 and mesh size 1.63. Exploration showed that that gear was prevalent through all years.
