### ISSUE TITLE
Repeat lit search on Scopus & Google Scholar

### ISSUE THREAD

**Issue by kfrasier** [NCEAS/oss-fishteam#26]
1) Repeat searches conducted on Web of Science on 2 additional platforms. (Grab first Nth results from google scholar? N=~50?)

2) Automate process of removing duplicates.

3) Figure out how many papers this adds.

Notes:  

If we're going to throw out any study that isn't in the Gulf of Mexico, it seems like we should modify our original search "'Red Snapper' Distribution"  to include "Gulf of Mexico". Is that ok with everyone?

Also, might be worth trying "habitat"?

**Comment by kfrasier** [comment]
Ended up using Proquest as the second database instead of Scopus because UCSD doesn't have access to the latter.
Currently working on identifying irrelevant papers in the expanded list.

**Comment by aesacco** [comment]
Perhaps another database you could include are the Academic Premier ones that universities typically provide students/faculty. That search engine, at least for my universities, allows you to search a number of academic publication databases

**Comment by aesacco** [comment]
I think adding "Gulf of Mexico" is a great idea. Adding habitat might bring in much more irrelevant papers than we want. This may not be an issue, however, if you're creating a script to automate the process. I'd love to see the final code!

**Comment by kfrasier** [comment]
@aesacco Thanks for the tip! I'll look into the Academic Premier option. My strategy so far for automation is a pretty basic string matching approach, so nothing too exciting :/

**Comment by aesacco** [comment]
@kfrasier Something like this http://web.a.ebscohost.com/ehost/search/advanced?vid=0&sid=8f3c0d43-0315-449d-b752-6af98967cf2e%40sessionmgr4010
EBSCOHost - that's another name for it (my brain was fuzzy from all the driving 🥇 )
