### ISSUE TITLE
GAM ensemble model to estimate abundance

### ISSUE THREAD

**Issue by aesacco** [NCEAS/oss-fishteam#29]
Creation of GAMs for both presence/absence data and CPUE data (density) to determine estimates of abundance across the study area.

**Comment by aesacco** [comment]
@cnglaspie is there any update on these models?

**Comment by cnglaspie** [comment]
![predictions](https://user-images.githubusercontent.com/27877364/40287651-b55eba8c-5c63-11e8-969d-329f017d4557.png)

I have some code that combines a Gaussian GAM for all positive CPUE, and a binomial GAM for presence/absence. The deviance explained is only 3.53% for the Gaussian model, but it is 17.1% for the binomial model. Combining these two models produced some predictions that closely match CPUE, and I think the spatial trends predicted make sense biologically. I did not add any additional variables to this analysis (bathymetry, etc.) but I can in the next iteration.
